# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: /css
  style: nested

exclude: ['post-receive', 'tags', '_includes/head.html', '_includes/navbar.html']
include: ['_includes']